const mongoose=require('mongoose')
const new_schema=mongoose.Schema
const user=new new_schema({
    username:{
        required:false,
        type:String
    },
    pin:{
        required:false,
        type:Number
    },
    aadhar_number:{
        required:false,
        type:Number
    },
    phoneno:{
        required:false,
        type:Number
    },
    
    account_number:{
        required:false,
        type:String
    },
    ifsc_code:{
        required:false,
        type:String
    },
    branch_name:{
        required:false,
        type:String
    },
    balance:{
        required:false,
        type:Number 
    },
    credit_card:{
        required:false,
        type:Number
    },
    cibil_score:{
        required:false,
        type:Number
    },
    type:{
        required:false,
        type:String 
    },
    email:{
        required:false,
        type:String 
    },
    address:{
        required:false,
        type:String 
    },
    otp_change_pin:{
        required:false,
        type:String,
        default:'not'
    },
    is_blocked:{
        required:false,
        type:Number,
        default:0
    },
    due_amount:{
        required:false,
        type:Number 
    }
},{versionKey:false})
const user_mod=mongoose.model('users',user)
module.exports=user_mod